export const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tiller · Keep your agent on course</title><link rel="stylesheet" href="/style.css"><script src="/app.js" defer></script></head><body>
<header><strong>↗ Tiller</strong><span>Keep your agent on course</span><button id="refresh">Refresh</button></header>
<main><aside><h2>Runs</h2><p class="muted">Recent local activity</p><div id="runs"></div></aside><section id="detail"><h1>Your execution timeline</h1><p>Select a run to inspect its plan, tool activity, checks, and patch.</p><p class="muted">Start a task with the CLI or the configured Tiller MCP server.</p></section></main>
<footer id="notice">Connecting to your local runtime…</footer></body></html>`;
const baseCss = `:root{color-scheme:dark;font-family:Inter,Segoe UI,sans-serif;background:#10141e;color:#e9eef6}*{box-sizing:border-box}body{margin:0}header{display:flex;align-items:center;gap:24px;padding:22px 32px;border-bottom:1px solid #2a3447;background:#151b29}header strong{font-size:26px;color:#93e6ba}header span,.muted{color:#9aa9bf}header button{margin-left:auto}button{background:#243247;color:#e9eef6;border:1px solid #43516c;border-radius:9px;padding:10px 14px;cursor:pointer}button:hover{border-color:#93e6ba}main{display:grid;grid-template-columns:320px 1fr;min-height:85vh}aside{padding:24px;border-right:1px solid #2a3447}section{padding:32px;min-width:0}h1{font-size:28px}h2{font-size:19px}h3{font-size:16px}.run{display:block;text-align:left;width:100%;margin-bottom:12px}.run small{display:block;color:#9aa9bf;margin-top:6px}.cards{display:flex;gap:16px;flex-wrap:wrap;margin:24px 0}.card{padding:18px;background:#1a2333;border:1px solid #2a3447;border-radius:12px;min-width:150px}.card strong{display:block;font-size:24px;margin-bottom:6px}.event{border-left:2px solid #43516c;margin:0 0 0 8px;padding:0 0 20px 20px}.event time{display:block;color:#9aa9bf;font-size:12px;margin:5px 0}.success{color:#93e6ba}.warning{color:#ffc980}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#151b29;padding:16px;border-radius:8px;max-height:420px;overflow:auto}footer{position:sticky;bottom:0;background:#151b29;padding:12px 32px;border-top:1px solid #2a3447;font-size:13px}@media(max-width:800px){main{grid-template-columns:1fr}aside{border-right:0;border-bottom:1px solid #2a3447}header span{display:none}section{padding:20px}}`;
export const css = baseCss + '.label{display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}aside{max-height:calc(100vh - 90px);overflow-y:auto;position:sticky;top:0}@media(max-width:800px){aside{max-height:250px;position:static}h1{font-size:22px}}';
export const js = `const token=location.hash.slice(1);history.replaceState(null,'',location.pathname);let selected=null;
const el=(tag,text,className)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node};
async function api(path,method='GET'){const response=await fetch(path,{method,headers:{Authorization:'Bearer '+token}});if(!response.ok)throw new Error('Request failed ('+response.status+')');return response.json()}
async function list(){try{const runs=await api('/api/runs');const host=document.querySelector('#runs');host.replaceChildren();for(const run of runs){const button=el('button',undefined,'run');button.append(el('span',run.goal,'label'),el('small',run.status+' · '+run.strategy));button.onclick=()=>show(run.id).catch(error=>document.querySelector('#notice').textContent=error.message);host.append(button)}document.querySelector('#notice').textContent='Local runtime · '+runs.length+' recent runs · Sensitive values masked in previews';if(selected)await show(selected)}catch(error){document.querySelector('#notice').textContent=error.message+' — reopen the dashboard URL printed by Tiller'}}
async function show(id){selected=id;const run=await api('/api/runs/'+id);const events=await api('/api/runs/'+id+'/events');const host=document.querySelector('#detail');host.replaceChildren(el('h1',run.goal),el('p',run.status+' · '+run.strategy+' · '+run.executionMode,run.status==='succeeded'?'success':'warning'),el('p',run.acceptance));
const cards=el('div',undefined,'cards');for(const [label,value] of [['Model calls',run.spent.modelCalls+' / '+run.budget.maxModelCalls],['Tool calls',run.spent.toolCalls+' / '+run.budget.maxToolCalls],['Generated tokens',run.spent.outputTokens],['Unknown usage calls',run.spent.unknownUsageCalls]]){const card=el('div',undefined,'card');card.append(el('strong',String(value)),el('span',label));cards.append(card)}host.append(cards);
if(run.message)host.append(el('p',run.message));if(run.remainingPlan.length){host.append(el('h2','Remaining plan'));const plan=el('ol');for(const step of run.remainingPlan)plan.append(el('li',step));host.append(plan)}
if(['ready','running','verifying','paused'].includes(run.status)){const cancel=el('button','Request cancellation');cancel.onclick=async()=>{await api('/api/runs/'+id+'/cancel','POST');await show(id)};host.append(cancel)}
if(run.status==='succeeded'){const patch=await api('/api/runs/'+id+'/patch');host.append(el('h2','Verified patch preview'),el('p','Review the original CLI artifact before applying; preview masking can change patch contents.','muted'),el('pre',patch.patch))}
if(run.hierarchy){host.append(el('h2','Work units'));const units=el('ul');for(const node of run.hierarchy.nodes)units.append(el('li',node.id+' · '+run.hierarchy.progress[node.id].status+' · '+node.goal));host.append(units)}if(matchMedia('(max-width:800px)').matches)host.scrollIntoView({behavior:'smooth',block:'start'});host.append(el('h2','Observed timeline'));for(const event of events){const row=el('div',undefined,'event');row.append(el('strong',event.type),el('time',new Date(event.at).toLocaleString()));const detail=JSON.stringify(event.details,null,2);if(detail!=='{}')row.append(el('pre',detail));host.append(row)}}
document.querySelector('#refresh').onclick=list;list();`;
